"""
Gemini service — converts a natural-language search into structured filters.

Only used by POST /search/natural. Never executes raw SQL generated by the
model; filters are applied through the same Supabase query builder used by
GET /persons so injection is not possible.
"""

from __future__ import annotations

import json
import re
from typing import Any, Dict

from config import get_settings
from schemas import NaturalSearchFilters
from services.gemini_client import get_generative_model

# Prompt that forces Gemini to reply with JSON matching NaturalSearchFilters.
_SYSTEM_PROMPT = """
You are a query parser for FindMyPal, a missing-persons search platform.

Convert the user's natural language search into JSON filters for a persons table.

Return ONLY a JSON object (no markdown, no explanation) with these optional keys:
- "name": string, partial name to match (null if not mentioned)
- "location": string, city/region/place keyword (null if not mentioned)
- "age_min": integer 0-150 (null if not mentioned)
- "age_max": integer 0-150 (null if not mentioned)
- "status": one of "active", "found", "closed" (default "active" unless user asks otherwise)
- "gender": string such as "male", "female", "non-binary" (null if not mentioned)

Rules:
- If the user says "around 30" or "about 30", use age_min=25 and age_max=35.
- If the user says "in their 20s", use age_min=20 and age_max=29.
- If only a single age is given, set both age_min and age_max to that age.
- Prefer status "active" unless the user explicitly asks for found/closed cases.
- Omit or null any field you cannot confidently infer.
""".strip()


def _extract_json(text: str) -> Dict[str, Any]:
    """
    Pull a JSON object out of a Gemini response.

    Handles plain JSON and fenced ```json blocks.
    """
    cleaned = text.strip()

    # Strip markdown fences if the model ignored instructions
    fence = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", cleaned, re.IGNORECASE)
    if fence:
        cleaned = fence.group(1).strip()

    # Fallback: first {...} block in the text
    if not cleaned.startswith("{"):
        brace = re.search(r"\{[\s\S]*\}", cleaned)
        if brace:
            cleaned = brace.group(0)

    data = json.loads(cleaned)
    if not isinstance(data, dict):
        raise ValueError("Gemini response was not a JSON object")
    return data


def query_to_filters(query: str) -> NaturalSearchFilters:
    """
    Ask Gemini to turn `query` into NaturalSearchFilters.

    Raises ValueError / RuntimeError on parse or API failures so the route
    can return a 502 with a clear message.
    """
    settings = get_settings()

    if not settings.gemini_api_key or settings.gemini_api_key.startswith("YOUR_"):
        raise RuntimeError(
            "GEMINI_API_KEY is not configured. Set it in backend/.env"
        )

    model = get_generative_model(system_instruction=_SYSTEM_PROMPT)

    response = model.generate_content(
        f'User search query: """{query}"""',
        generation_config={
            "temperature": 0.1,
            "response_mime_type": "application/json",
        },
    )

    raw_text = getattr(response, "text", None) or ""
    if not raw_text.strip():
        raise ValueError("Gemini returned an empty response")

    try:
        payload = _extract_json(raw_text)
    except (json.JSONDecodeError, ValueError) as exc:
        raise ValueError(f"Could not parse Gemini JSON: {exc}") from exc

    # Drop nulls so Pydantic defaults (e.g. status=active) still apply
    sanitized = {k: v for k, v in payload.items() if v is not None}
    return NaturalSearchFilters(**sanitized)
