// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AlertSubscriptions = __t.object("AlertSubscriptions", {
  id: __t.string(),
  kind: __t.string(),
  email: __t.string(),
  queryText: __t.option(__t.string()),
  zipCode: __t.option(__t.string()),
  personId: __t.option(__t.string()),
  active: __t.bool(),
  createdAt: __t.string(),
});
export type AlertSubscriptions = __Infer<typeof AlertSubscriptions>;

export const BackendAccess = __t.object("BackendAccess", {
  id: __t.string(),
  identity: __t.identity(),
});
export type BackendAccess = __Infer<typeof BackendAccess>;

export const CaseActivity = __t.object("CaseActivity", {
  id: __t.string(),
  personId: __t.string(),
  personName: __t.string(),
  kind: __t.string(),
  createdAt: __t.string(),
});
export type CaseActivity = __Infer<typeof CaseActivity>;

export const CaseCoordinators = __t.object("CaseCoordinators", {
  id: __t.string(),
  personId: __t.string(),
  email: __t.string(),
  role: __t.string(),
  createdAt: __t.string(),
});
export type CaseCoordinators = __Infer<typeof CaseCoordinators>;

export const CaseSourceLinks = __t.object("CaseSourceLinks", {
  id: __t.string(),
  personId: __t.string(),
  title: __t.string(),
  url: __t.string(),
  sourceType: __t.string(),
  publishedAt: __t.option(__t.string()),
  createdAt: __t.string(),
});
export type CaseSourceLinks = __Infer<typeof CaseSourceLinks>;

export const CaseUpdates = __t.object("CaseUpdates", {
  id: __t.string(),
  personId: __t.string(),
  authorEmail: __t.option(__t.string()),
  body: __t.string(),
  createdAt: __t.string(),
});
export type CaseUpdates = __Infer<typeof CaseUpdates>;

export const EmailOutboxLog = __t.object("EmailOutboxLog", {
  id: __t.string(),
  toEmail: __t.string(),
  subject: __t.string(),
  body: __t.string(),
  kind: __t.option(__t.string()),
  meta: __t.option(__t.string()),
  createdAt: __t.string(),
});
export type EmailOutboxLog = __Infer<typeof EmailOutboxLog>;

export const LiveTipEvents = __t.object("LiveTipEvents", {
  id: __t.string(),
  personId: __t.option(__t.string()),
  personName: __t.option(__t.string()),
  snippet: __t.option(__t.string()),
  createdAt: __t.string(),
});
export type LiveTipEvents = __Infer<typeof LiveTipEvents>;

export const Persons = __t.object("Persons", {
  id: __t.string(),
  name: __t.string(),
  age: __t.i32(),
  gender: __t.option(__t.string()),
  lastSeenLocation: __t.string(),
  lastSeenDate: __t.string(),
  description: __t.string(),
  photoUrl: __t.option(__t.string()),
  status: __t.string(),
  policeReportNumber: __t.option(__t.string()),
  createdAt: __t.string(),
  aiSummary: __t.option(__t.string()),
  aiSummaryUpdatedAt: __t.option(__t.string()),
  verifiedPoliceReport: __t.bool(),
  lastVerifiedAt: __t.option(__t.string()),
  foundAt: __t.option(__t.string()),
  foundMessage: __t.option(__t.string()),
  watchersCount: __t.i32(),
  sharesCount: __t.i32(),
  tipsCount: __t.i32(),
  suspiciousFlags: __t.i32(),
  underReview: __t.bool(),
  demoTag: __t.option(__t.string()),
  ownerToken: __t.option(__t.string()),
  contactEmail: __t.option(__t.string()),
  lastSeenTime: __t.option(__t.string()),
  sourceListingUrl: __t.option(__t.string()),
  sourceAgencyName: __t.option(__t.string()),
  externalCaseNumber: __t.option(__t.string()),
  sourceLastCheckedAt: __t.option(__t.string()),
});
export type Persons = __Infer<typeof Persons>;

export const ProfileFlags = __t.object("ProfileFlags", {
  id: __t.string(),
  personId: __t.string(),
  reason: __t.option(__t.string()),
  reporterIp: __t.option(__t.string()),
  createdAt: __t.string(),
});
export type ProfileFlags = __Infer<typeof ProfileFlags>;

export const SearchMemory = __t.object("SearchMemory", {
  id: __t.string(),
  participantKey: __t.string(),
  city: __t.option(__t.string()),
  dateFrom: __t.option(__t.string()),
  dateTo: __t.option(__t.string()),
  filtersJson: __t.option(__t.string()),
  updatedAt: __t.string(),
});
export type SearchMemory = __Infer<typeof SearchMemory>;

export const Sightings = __t.object("Sightings", {
  id: __t.string(),
  personId: __t.string(),
  locationLat: __t.f64(),
  locationLng: __t.f64(),
  dateTime: __t.string(),
  description: __t.string(),
  confidenceLevel: __t.i32(),
  submitterEmail: __t.option(__t.string()),
  createdAt: __t.string(),
  credibilityScore: __t.option(__t.i32()),
  familyReviewFlag: __t.bool(),
  credibilityReasons: __t.option(__t.string()),
});
export type Sightings = __Infer<typeof Sightings>;

export const TipClusters = __t.object("TipClusters", {
  id: __t.string(),
  personId: __t.string(),
  centerLat: __t.f64(),
  centerLng: __t.f64(),
  radiusKm: __t.f64(),
  tipCount: __t.i32(),
  windowStart: __t.string(),
  windowEnd: __t.string(),
  label: __t.option(__t.string()),
  notified: __t.bool(),
  createdAt: __t.string(),
});
export type TipClusters = __Infer<typeof TipClusters>;

export const Users = __t.object("Users", {
  id: __t.string(),
  email: __t.string(),
  role: __t.string(),
  createdAt: __t.string(),
});
export type Users = __Infer<typeof Users>;

export const WriteReceipts = __t.object("WriteReceipts", {
  id: __t.string(),
  fingerprint: __t.string(),
  result: __t.string(),
  createdAt: __t.string(),
});
export type WriteReceipts = __Infer<typeof WriteReceipts>;

