// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as ExecuteQueryProcedure from "../execute_query_procedure";

export type ExecuteQueryArgs = __Infer<typeof ExecuteQueryProcedure.params>;
export type ExecuteQueryResult = __Infer<typeof ExecuteQueryProcedure.returnType>;

