<#
.SYNOPSIS
  Option A: expose local FindMyPal via Cloudflare quick tunnels (demo URL).

.DESCRIPTION
  1) Installs cloudflared if missing
  2) Opens a public HTTPS URL to Vite (:5173) — API is proxied same-origin
  3) Opens a second public URL to SpacetimeDB (:3000) for live WS
  4) Writes frontend/.env.tunnel with the Spacetime WSS URL

  Keep this window open while demoing. Ctrl+C stops the tunnels.
#>

$ErrorActionPreference = "Stop"
$Root = Resolve-Path (Join-Path $PSScriptRoot "..")

function Ensure-Cloudflared {
  $local = Join-Path $Root "scripts\tools\cloudflared.exe"
  if (Test-Path $local) { return $local }
  $cmd = Get-Command cloudflared -ErrorAction SilentlyContinue
  if ($cmd) { return $cmd.Source }
  throw "cloudflared missing. Expected at scripts/tools/cloudflared.exe"
}

function Start-QuickTunnel([string]$Cloudflared, [string]$Url, [string]$LogPath) {
  if (Test-Path $LogPath) { Remove-Item $LogPath -Force }
  $proc = Start-Process -FilePath $Cloudflared `
    -ArgumentList @("tunnel", "--url", $Url, "--no-autoupdate") `
    -RedirectStandardError $LogPath `
    -RedirectStandardOutput $LogPath `
    -PassThru -WindowStyle Hidden
  return $proc
}

function Wait-TunnelUrl([string]$LogPath, [int]$TimeoutSec = 45) {
  $deadline = (Get-Date).AddSeconds($TimeoutSec)
  while ((Get-Date) -lt $deadline) {
    Start-Sleep -Seconds 1
    if (-not (Test-Path $LogPath)) { continue }
    $text = Get-Content $LogPath -Raw -ErrorAction SilentlyContinue
    if (-not $text) { continue }
    $m = [regex]::Match($text, "https://[a-z0-9-]+\.trycloudflare\.com")
    if ($m.Success) { return $m.Value }
  }
  throw "Timed out waiting for tunnel URL. Log:`n$(Get-Content $LogPath -Raw -ErrorAction SilentlyContinue)"
}

Write-Host "== FindMyPal demo tunnel (Option A) =="
$cf = Ensure-Cloudflared
Write-Host "cloudflared: $cf"

# Verify local services
foreach ($port in @(5173, 8000, 3000)) {
  $listening = Get-NetTCPConnection -LocalPort $port -State Listen -ErrorAction SilentlyContinue
  if (-not $listening) {
    Write-Warning "Nothing listening on port $port. Start Vite/API/Spacetime before demos."
  } else {
    Write-Host "OK port $port"
  }
}

$logDir = Join-Path $Root "scripts\.tunnel-logs"
New-Item -ItemType Directory -Force -Path $logDir | Out-Null
$webLog = Join-Path $logDir "web.err.log"
$stLog = Join-Path $logDir "spacetime.err.log"

Write-Host "Starting web tunnel -> http://127.0.0.1:5173 ..."
$webProc = Start-QuickTunnel $cf "http://127.0.0.1:5173" $webLog
$webUrl = Wait-TunnelUrl $webLog
Write-Host "WEB  $webUrl"

Write-Host "Starting Spacetime tunnel -> http://127.0.0.1:3000 ..."
$stProc = Start-QuickTunnel $cf "http://127.0.0.1:3000" $stLog
$stHttp = Wait-TunnelUrl $stLog
$stWs = $stHttp -replace "^https://", "wss://"
Write-Host "SPACETIME WS  $stWs"

$envTunnel = @"
# Auto-generated by scripts/demo_tunnel.ps1 — for Cloudflare Tunnel demos
# Copy into frontend/.env (or restart Vite after merging) then hard-refresh.

VITE_API_BASE_URL=
VITE_SPACETIMEDB_URI=$stWs
VITE_SPACETIMEDB_DATABASE=findmypal
"@
$outEnv = Join-Path $Root "frontend\.env.tunnel"
Set-Content -Path $outEnv -Value $envTunnel -Encoding UTF8
Write-Host "Wrote $outEnv"

# Apply for current Vite if we can (user must restart Vite to pick up env)
$frontendEnv = Join-Path $Root "frontend\.env"
$backup = Join-Path $Root "frontend\.env.localbackup"
if (Test-Path $frontendEnv) {
  Copy-Item $frontendEnv $backup -Force
}
Set-Content -Path $frontendEnv -Value $envTunnel -Encoding UTF8
Write-Host "Updated frontend/.env for tunnel mode (backup: .env.localbackup)"
Write-Host ""
Write-Host "NEXT STEPS:"
Write-Host "  1. Restart Vite (Ctrl+C in frontend terminal, then npm run dev)"
Write-Host "  2. Open this URL on another phone/laptop: $webUrl"
Write-Host "  3. Keep this script running (tunnels die when it exits)"
Write-Host ""
Write-Host "Press Ctrl+C to stop tunnels and restore local .env ..."

try {
  while ($true) {
    if ($webProc.HasExited -or $stProc.HasExited) {
      Write-Warning "A tunnel process exited. Check logs in $logDir"
      break
    }
    Start-Sleep -Seconds 5
  }
} finally {
  Write-Host "Stopping tunnels..."
  foreach ($p in @($webProc, $stProc)) {
    try { if ($p -and -not $p.HasExited) { Stop-Process -Id $p.Id -Force } } catch {}
  }
  if (Test-Path $backup) {
    Copy-Item $backup $frontendEnv -Force
    Write-Host "Restored frontend/.env from backup"
  }
}
